# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\Build.ps1

test: off

artifacts:
- path: .\**\*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: wsLtl0n7iO6nyH44qhjh8EsVtzoV+5URLhQMBCVzHv3Td3rV8zgkjX7++s19LhF3
    skip_symbols: true
    on:
      branch: master